### ISSUE TITLE
Mainline builds are set to track master and not main

### ISSUE THREAD

**Issue by ncatelli** [ncatelli/keebler#15]
Builds are not happening on the protected branch due to it being set to build on master.

```yaml
on: 
  push:
    branches:
      - master
```
